Fix typo discovered by codespell
PythonTurtle/PythonTurtle pull request #145
Opened 2020-09-20 21:18 UTC by cclauss

2020-09-20 21:24 UTC, bittner requested changes
Hi @cclauss, thanks for your contribution!

Would you mind squashing the two changes into a single commit?

Afterwards it would be ready for merging. :+1:

2020-09-20 21:37 UTC, cclauss commented
The GitHub web UI does not allow contributors  to squash commits but it does allow maintainers to squash and merge at the click of a button.

2020-09-20 21:42 UTC, bittner commented
> The GitHub web UI does not allow contributors to squash commits but it does allow maintainers to squash and merge at the click of a button.

I know. But we have it configured in a way that squashing is disabled from the UI. (I have to change the settings just for being able to do that.)

Apart from that, you'd have a clean contribution, a single commit just with your name as a contributor if you squad the commits on the command line. If you don't worry about that I'm fine to go ahead as you suggested.

2020-09-21 01:04 UTC, bittner approved these changes

2020-09-21 01:04 UTC, merged